name: Build Volleyball plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Volleyball
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clone and build canvas
        run: |
          git clone https://github.com/IPVP-MC/canvas.git
          cd canvas
          mvn clean install

      - name: Build Volleyball
        run: mvn clean package

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: Volleyball-Plugin
          path: target/*.jar
